name: Build and Generate APK

on:
  workflow_dispatch:
    inputs:
      api_link:
        description: 'API Link'
        required: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: 'x64'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Replace API Link
        run: sed -i '' "s|https://prod.apis.simpleviralgames.com/game/slug/water-sort-2?language=en|${{ github.event.inputs.api_link }}|g" /Users/janvikumari/AndroidStudioProjects/simpleviralgames2/app/src/main/java/com/example/simpleviralgames/repository/gameRepository.kt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Updated API Link"
          git push

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: /Users/janvikumari/AndroidStudioProjects/simpleviralgames2/app/build/outputs/apk/debug/app-debug.apk
