on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and generate APK
        run: |
          cd /Users/janvikumari/AndroidStudioProjects/simpleviralgames2
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: /Users/janvikumari/AndroidStudioProjects/simpleviralgames2/app/build/outputs/apk/debug/app-debug.apk
